#!/bin/bash

IMAGE_VERSION=0.0.15
IMAGE_NAME="vakaras/viper-build:${IMAGE_VERSION}"

echo 'This will take a lot of time...'

#if [ "$EUID" -ne 0 ]; then
#  echo "To build a Docker image, you need to be root."
#  echo "Using sudo to get root permissions:"
#  sudo docker build -t "${IMAGE_NAME}" .
#else
  docker build -t "${IMAGE_NAME}" .
#fi
